accounts/urls.py
from django.conf.urls import url
from . import views

app_name='accounts'

urlpatterns = [
   url(r'^signup/$', views.signup_view, name="signup"),
   url(r'^login/$',views.login_view, name="login"),
   url(r'^logout/$', views.logout_view, name="logout"),

]

contact/urls.py
from django.conf.urls import url, include
from . import views
from django.conf import settings
from django.core.mail import EmailMessage
urlpatterns = [

    url(r'^$', views.contact, name='contact'),


]

main/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [

    url(r'^$', views.index, name='index'),
    

]

news/urls.py
from django.conf.urls import url, include
from django.views.generic import ListView, DetailView
from news.models import Articles
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static



urlpatterns = [
    url(r'^$', ListView.as_view(queryset=Articles.objects.all().order_by("-date")[:20],
        template_name="news/posts.html")),
    url(r'^(?P<pk>\d+)$', DetailView.as_view(model=Articles, template_name="news/post.html")),

       ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

taskfive/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [

    url(r'^$', views.index, name='index'),


]

taskfour/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [

    url(r'^$', views.index, name='index'),


]

webquest/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('main.urls')),
    url(r'^taskone/', include('taskone.urls')),
    url(r'^tasktwo/', include('tasktwo.urls')),
    url(r'^taskthree/', include('taskthree.urls')),
    url(r'^taskfour/', include('taskfour.urls')),
    url(r'^taskfive/', include('taskfive.urls')),
    url(r'^kriteri/', include('kriteri.urls')),
    url(r'^contact/', include('contact.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^news/', include('news.urls')),
    url(r'^tasksix/', include('tasksix.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models
class Articles(models.Model):
    title = models.CharField(max_length = 500)
    post = models.TextField()
    date = models.DateTimeField()
    image=models.ImageField("Изображение", upload_to="media/")


    def __str__(self):
        return self.title

accounts/forms.py
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm

class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254)
    first_name = forms.CharField(max_length=254)
    class Meta:
        model = User
        fields = ('username', 'first_name', 'email','password1', 'password2')

contact/forms.py
from django import forms
class ContactForm(forms.Form):

    contact_email = forms.EmailField(required=True)
    content = forms.CharField(
        required=True,
        widget=forms.Textarea
    )
    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)

        self.fields['contact_email'].label = "Ваш email:"
        self.fields['content'].label = "Ваш вопрос или пожелание:"

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from . forms import UserRegistrationForm
# Create your views here.
def signup_view(request):
    if request.method=='POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return render(request, 'accounts/register_done.html')
    else:
        form = UserRegistrationForm ()
    return render(request, 'accounts/signup.html',{'form': form})
def login_view(request):
    if request.method=='POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('/')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'form':form})
def logout_view(request):
    if request.method=='POST':
        logout(request)
        return redirect('/')

contact/views.py
from django.shortcuts import render
from contact.forms import ContactForm
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template.loader import get_template
from django.http import HttpResponse

def index(request):
    return render(request, 'contact/about.html')
def contact(request):
    form_class = ContactForm
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():

            contact_email = request.POST.get(
                'contact_email'
            , '')
            form_content = request.POST.get('content', '')

            template = get_template('contact/about_template.txt')
            context = {
                
                'contact_email': contact_email,
                'form_content': form_content,
            }
            content = template.render(context)

            email = EmailMessage(
                "Новая форма обратной связи",
                content,
                "Мой сайт" +'',
                ['alexsander.golubnik@gmail.com'],
                headers = {'Reply-To': contact_email }
            )
            email.send()
            return redirect('contact')

    return render(request, 'contact/about.html', {
        'form': form_class,
    })

kriteri/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'kriteri/kriteri.html')

main/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'main/index.html')

news/views.py
from django.shortcuts import render

# Create your views here.

taskfive/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'taskfive/task5.html')

taskfour/views.py
from django.shortcuts import render
def index(request):
    return render(request, 'taskfour/task4.html')

taskone/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'taskone/task1.html')

tasksix/views.py
from django.shortcuts import render
def index(request):
    return render(request, 'tasksix/task6.html')

taskthree/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'taskthree/task3.html')

tasktwo/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'tasktwo/task2.html')

accounts/templates/accounts/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="icon" href="{% static 'img/icon.svg' %}">
  <link href="https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <title>Авторизация</title>
<body>
  <header>
    <nav>
      <ul class="topmenu">
        <li><a href="/">Главная</a></li>
        <li><a href="/news">Новости</a></li>
        {% if user.is_authenticated %}
        <li><a href="" class="down">Задания</a>
          <ul class="submenu">
            <li><a href="/taskone">Задание 1</a></li>
            <li><a href="/tasktwo">Задание 2</a></li>
            <li><a href="/taskthree">Задание 3</a></li>
            <li><a href="/taskfour">Задание 4</a></li>
            <li><a href="/taskfive">Задание 5</a></li>
            <li><a href="/tasksix">Задание 6</a></li>
          </ul>
        </li>
        {% endif %}
        <li><a href="/kriteri">Критерии оценивания</a></li>
        <li><a href="/contact">Контакты</a></li>
        {% if user.is_authenticated %}

                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                    <h4> {{ user.first_name }}!</h4>
                  <button type="submit" class="btn btn-danger btn-lg">Выход</button>
                </form>

              {% else %}
        <a class="btn btn-outline-primary" href="/accounts/login">Войти</a>
    <a class="btn btn-outline-primary" href="/accounts/signup">Регистрация</a>
    {% endif %}
    <br>
      </ul>

    </nav>


  </header>
  <br>

    <div id="blue">
      <div class="container">
        <div class="row centered">
          <div class="col-lg-8 col-lg-offset-2">
        <h1>Авторизация</b></h1>
      </div>
    </div>
    <!-- row -->
  </div>
  <!-- container -->
</div>
<!--  bluewrap -->
<div class="container mt-4">
  <h1><i class="fa fa-user-circle"></i> Пожалуйста, авторизируйтесь:</h1>
  <hr>
  <br>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    <p>Введите логин</p>
    {{ form.username }}<br><br>
    <p>Введите пароль</p>
    {{ form.password }}<br>
    {% if request.GET.next %}
       <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <br>
    <hr>
    <button class="btn btn-success" type="submit">Вход</button>
    </form>

</div>
<br>
<div class="container mt-4">
<p>Ещё не зарегистрировались? <a href="/accounts/signup">Зарегистрировать команду</a></p>
</div>
{% block contents %}
{% include "main/includes/footer.html" %}
{% endblock %}
</body>
</html>

accounts/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="icon" href="{% static 'img/icon.svg' %}">
  <link href="https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <title>Регистрация</title>
</head>
<body>
  <header>
    <nav>
      <ul class="topmenu">
        <li><a href="/">Главная</a></li>
        <li><a href="/news">Новости</a></li>
        {% if user.is_authenticated %}
        <li><a href="" class="down">Задания</a>
          <ul class="submenu">
            <li><a href="/taskone">Задание 1</a></li>
            <li><a href="/tasktwo">Задание 2</a></li>
            <li><a href="/taskthree">Задание 3</a></li>
            <li><a href="/taskfour">Задание 4</a></li>
            <li><a href="/taskfive">Задание 5</a></li>
            <li><a href="/tasksix">Задание 6</a></li>
          </ul>
        </li>
        {% endif %}
        <li><a href="/kriteri">Критерии оценивания</a></li>
        <li><a href="/contact">Контакты</a></li>
        {% if user.is_authenticated %}

                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                    <h4> {{ user.first_name }}!</h4>
                  <button type="submit" class="btn btn-danger btn-lg">Выход</button>
                </form>

              {% else %}
        <a class="btn btn-outline-primary" href="/accounts/login">Войти</a>
    <a class="btn btn-outline-primary" href="/accounts/signup">Регистрация</a>
    {% endif %}
    <br>
      </ul>

    </nav>


  </header>
  <br>

    <div id="blue">
      <div class="container">
        <div class="row centered">
          <div class="col-lg-8 col-lg-offset-2">
        <h1>Регистрация</b></h1>
      </div>
    </div>
    <!-- row -->
  </div>
  <!-- container -->
</div>
<!--  bluewrap -->
<div class="container mt-4">
  <h1><i class="fa fa-id-card"></i> Форма регистрации команды</h1>
  <hr>
  <br>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    <p>Введите логин</p>
    {{ form.username }} <br><br>
    <p>Введите название команды</p>
    {{ form.first_name }} <br><br>
    <p>Введите email</p>
    {{ form.email }} <br><br>
    <p>Введите пароль (пароль должен содержать латинские буквы, заглавные и маленькие, а также символы: -.,..)</p>
    {{ form.password1 }} <br><br>
    <p>Подтвердите пароль</p>
    {{ form.password2 }} <br>
     <br>
     <hr>
    <button class="btn btn-success" type="submit">Зарегистрировать</button>
    </form>

</div>
<br>
{% block contents %}
{% include "main/includes/footer.html" %}
{% endblock %}
</body>
</html>

contact/templates/contact/about.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="icon" href="{% static 'img/icon.svg' %}">
  <link href="https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <title>Контакты</title>
</head>
<body>
  <header>
    <nav>
      <ul class="topmenu">
        <li><a href="/">Главная</a></li>
        <li><a href="/news">Новости</a></li>
        {% if user.is_authenticated %}
        <li><a href="" class="down">Задания</a>
          <ul class="submenu">
            <li><a href="/taskone">Задание 1</a></li>
            <li><a href="/tasktwo">Задание 2</a></li>
            <li><a href="/taskthree">Задание 3</a></li>
            <li><a href="/taskfour">Задание 4</a></li>
            <li><a href="/taskfive">Задание 5</a></li>
            <li><a href="/tasksix">Задание 6</a></li>
          </ul>
        </li>
        {% endif %}
        <li><a href="/kriteri">Критерии оценивания</a></li>
        <li><a href="/contact">Контакты</a></li>
        {% if user.is_authenticated %}

                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                    <h4> {{ user.first_name }}!</h4>
                  <button type="submit" class="btn btn-danger btn-lg">Выход</button>
                </form>

              {% else %}
        <a class="btn btn-outline-primary" href="/accounts/login">Войти</a>
    <a class="btn btn-outline-primary" href="/accounts/signup">Регистрация</a>
    {% endif %}
    <br>
      </ul>

    </nav>


  </header>
  <br>

    <div id="blue">
      <div class="container">
        <div class="row centered">
          <div class="col-lg-8 col-lg-offset-2">
        <h1>Связь с нами</b></h1>
      </div>
    </div>
    <!-- row -->
  </div>
  <!-- container -->
</div>
<!--  bluewrap -->
<br>
  {% csrf_token %}
<div class="container mt-5">
  <h3>Наши контакты</h3><br>
  <p>Связаться с нами вы можете через социальные сети, а также можете задать свой вопрос через форму ниже.</p>
  <li><a href="https://vk.com/agolubnik">Александр Голубник</a></li>
  <li><a href="https://vk.com/idkatekoval">Екатерина Мартынкова</a></li>
</div>
<div class="container mt-5">
  <h3>Дорогой участник образовательного Web-квеста по вепсской культуре! Просим тебя оставить отзыв о нашем квесте.</h3>
  <a href="https://docs.google.com/forms/d/1Hk16rGkhAKNvaLNGdTXgAl2Jx5lZmXvSvsMskdZzqvI/">Анкета</a>
</div>
<div class="container mt-5">
<h3><i class="fa fa-envelope-open"></i> Обратная связь:</h3>
<hr>
<br>
<form role="form" action="" method="post">
  {% csrf_token %}
    {{ form.as_p }}
    <hr>
  <button type="submit" name="send" class="btn btn-success">Отправить</button>
</form>
</div>
<br>
{% block contents %}
{% include "main/includes/footer.html" %}
{% endblock %}



</body>
</html>

kriteri/templates/kriteri/kriteri.html
<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  {% load static %}
  <link rel="icon" href="{% static 'img/icon.svg' %}">
  <link href="https://fonts.googleapis.com/css2?family=Sansita+Swashed:wght@300&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
  <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  <title>Критерии оценивания</title>
</head>
<body>
  <header>
    <nav>
      <ul class="topmenu">
        <li><a href="/">Главная</a></li>
        <li><a href="/news">Новости</a></li>
        {% if user.is_authenticated %}
        <li><a href="" class="down">Задания</a>
          <ul class="submenu">
            <li><a href="/taskone">Задание 1</a></li>
            <li><a href="/tasktwo">Задание 2</a></li>
            <li><a href="/taskthree">Задание 3</a></li>
            <li><a href="/taskfour">Задание 4</a></li>
            <li><a href="/taskfive">Задание 5</a></li>
            <li><a href="/tasksix">Задание 6</a></li>
          </ul>
        </li>
        {% endif %}
        <li><a href="/kriteri">Критерии оценивания</a></li>
        <li><a href="/contact">Контакты</a></li>
        {% if user.is_authenticated %}

                <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                  {% csrf_token %}
                    <h4> {{ user.first_name }}!</h4>
                  <button type="submit" class="btn btn-danger btn-lg">Выход</button>
                </form>

              {% else %}
        <a class="btn btn-outline-primary" href="/accounts/login">Войти</a>
    <a class="btn btn-outline-primary" href="/accounts/signup">Регистрация</a>
    {% endif %}
    <br>
      </ul>

    </nav>


  </header>
  <br>

    <div id="blue">
      <div class="container">
        <div class="row centered">
          <div class="col-lg-8 col-lg-offset-2">
        <h1>Критерии оценивания</b></h1>
      </div>
    </div>
    <!-- row -->
  </div>
  <!-- container -->
</div>
<!--  bluewrap -->
<br></br>
<div class="row">
  <div class="col">
<div class="container">
  <h3>Спасибо за то, что участвовали в нашем Web квесте</h3><br>
  <p>Ниже вы найдете критерии оценивания вашей финальной работы</p><br>
</div>
</div>
<div class="col">
  <img src="{% static 'img/brusnika.jpg' %}" class="img-thumbnail" width=150 heght=150>
</div>
</div>
<br>
<table class="table table-bordered">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Критерии</th>
      <th scope="col">Обоснование критериев</th>
      <th scope="col">Баллы</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th rowspan="3">Содержание</th>
      <td>Понимание задания</td>
      <td><li>Работа демонстрирует точное понимание задания</li><br>
      <li>Включаются как материалы, имеющие непосредственное отношение к теме, так и материалы, не имеющие отношения к ней</li><br>
    <li>Включены материалы, не имеющие непосредственного отношения к теме</li> </td>
      <td>10<br><br>
      5<br><br>
    0</td>
    </tr>
    <tr>
      <td>Полнота раскрытия темы</td>
      <td><li>Полно</li><br>
      <li>Частично</li><br>
    <li>Не раскрыта</li><br></td>
      <td>10<br><br>
      5<br><br>
    0</td>

    </tr>
    <tr>
      <td>Логика изложения информации</td>
      <td><li>Логичное изложение информации</li><br>
      <li>Нарушение логики</li><br>
    <li>Отсутствие логики</li><br></td>
      <td>10<br><br>
      5<br><br>
    0</td>
    </tr>
    <tr>
      <th rowspan="3">Самостоятельная работа группы</th>
      <td>Слаженная работа в группе</td>
      <td><li>Четко спланированная работа группы</li><br>
      <li>Работа группы частично спланирована</li><br>
    <li>Не спланирована работа в группе</li><br></td>
    <td>10<br><br>
    5<br><br>
  0</td>
</tr>
<tr>
  <td>Распределение ролей в группе</td>
  <td><li>Вся деятельность равномерна распределена между членами команды</li><br>
  <li>Работа над материалом равномерно распределена между большинством участников команды</li><br>
  <li>Несколько членов группы отвечают за работу всей команды</li></td>
  <td>10<br><br>
    5<br><br>
    0</td>
  </tr>
  <tr>
    <td>Степень самостоятельности работы группы</td>
    <td><li>Полная самостоятельность при выполнении работы</li><br>
    <li>Частичная самостоятельность работы группы</li><br>
    <li>Несамостоятельная работы группы</li></td>
    <td>10<br><br>
      5<br><br>
      0</td>
    </tr>
    <tr>
      <th scope="row">Оформление работы</th>
      <td>Грамматика, подходящий словарь, отсутствие ошибок правописания и опечаток</td>
      <td><li>Грамотная работа с точки зрения грамматики, стилистики, орфографии</li><br>
      <li>Не грубые ошибки с точки зрения грамматики, стилистики, орфографии</li><br>
      <li>Грубые ошибки с точки зрения грамматики, стилистики, орфографии</li></td>
      <td>10<br><br>
        5<br><br>
        0</td>
      </tr>

  </tbody>
</table>
<div class="row">
  <div class="col">
    <div class="container ml-5">
    <img src="{% static 'img/veps.jpg' %}" class="img-thumbnail" width=200 heght=200>
  </div>
</div>
  <div class="col">

<h4>Итого:</h4><br>
<p>60-70 баллов - "отлично"</p><br>
<p>45 - 59 баллов - "хорошо"</p><br>
<p>30 - 44 баллов - "удовлетворительно"</p>

</div>
</div>
{% block contents %}
{% include "main/includes/footer.html" %}
{% endblock %}
</body>
</html>